In [9]:
import numpy as np

In [7]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0])

[1 2 3 4]


In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
print(np.arange(4))
print(np.arange(1,10,2))

[0 1 2 3]
[1 3 5 7 9]


In [10]:
myArray=np.array([1,2,3,4,5,6])

In [6]:
multipleArray= myArray * 5

In [15]:
print(multipleArray)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [17]:
myArray=np.array([1,2,3,4,5,6])

In [18]:
kaliArray= myArray * 5

In [19]:
print(kaliArray)

[ 5 10 15 20 25 30]


In [20]:
bagiArray=myArray / 5
print(bagiArray)

[0.2 0.4 0.6 0.8 1.  1.2]


In [21]:
tambahArray=myArray + 5
print(tambahArray)

[ 6  7  8  9 10 11]


In [22]:
kurangArray=myArray - 5
print(kurangArray)

[-4 -3 -2 -1  0  1]


In [24]:
#boolean
ismyMoreArraythan3 = myArray > 3

In [25]:
ismyMoreArraythan3

array([False, False, False,  True,  True,  True])

In [27]:
#filtering
valueArraythan3 = myArray[myArray > 3]
valueArraythan3

array([4, 5, 6])

In [33]:
#array 2D
array2D = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
print(array2D.shape)

(3, 4)


In [37]:
print(array2D[0,3])
print(array2D[0][3])

4
4


In [50]:
print(array2D[:,1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [54]:
#import data from csv
mystudentData=np.genfromtxt("./data.csv",skip_header=1,delimiter=",",filling_values=40)
print(mystudentData)

[[10. 20. 30. 40.]
 [50. 60. 70. 80.]
 [90. 20. 80. 80.]
 [50. 70. 80. 60.]]


In [65]:
maxInClass=np.amax(mystudentData,axis=0)
print(maxInClass)

90.0


In [67]:
mystudentData=np.append(mystudentData,[1,2,3,4],axis=0)
mystudentData

array([10., 20., 30., 40., 50., 60., 70., 80., 90., 20., 80., 80., 50.,
       70., 80., 60.,  1.,  2.,  3.,  4.,  1.,  2.,  3.,  4.,  1.,  2.,
        3.,  4.,  1.,  2.,  3.,  4.,  1.,  2.,  3.,  4.,  1.,  2.,  3.,
        4.,  1.,  2.,  3.,  4.,  1.,  2.,  3.,  4.])

In [68]:
DataUlangan=np.genfromtxt("./ulangan.csv",skip_header=1,delimiter=",",filling_values=40)
print(DataUlangan)

[[70. 75. 80. 30.]
 [75. 80. 90. 68.]
 [65. 77. 60. 90.]
 [40. 60. 55. 75.]]


In [85]:
sumDataUlangan=np.sum(DataUlangan,axis=0)
print(sumDataUlangan)

[250. 292. 285. 263.]


<function numpy.arange>

In [82]:
[y,x]=DataUlangan.shape
y
DataUlangan[2:y,3:x]

array([[90.],
       [75.]])

In [89]:
newData=np.delete(DataUlangan,[3],axis=0)
DataUlangan

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.],
       [40., 60., 55., 75.]])

In [90]:
DataUlangan

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.],
       [40., 60., 55., 75.]])

In [91]:
newData

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.]])

In [ ]:
ReshapeData=np.reshape(DataUlangan,)

In [93]:
#1D to 2D
oneDarray=[1,2,3,4,5,6,7,8,9,10]

In [95]:
twoDarray=oneDarray.reshape(5,2)

AttributeError: 'list' object has no attribute 'reshape'

In [ ]:
array_1=np.array([
    [1,3,5]
    [4,4,4]
])
array_2=np.array([
    []
])