# deskriptif statistic
meringkas, mengatur, mudah difahami, tidak membuat kesimpulan
# yang diukur 
* centar tendency(nilai tengah)
    - average/mean
    - median
    - stdv
    - mode/modus
* spread(sebaran)
    - stdv
    - mean deviasion
    - varian
    - percentil
    - quadratil
    
# Bentuk kurva
* Berdasarkan nilai tengah
    - positif skew
    - simetrical skew
    - negative skew
* Berdasarkan Sebaran (kurtosis)
    - Leprokurtic
    - Mesokurtic
    - platykurtic
    
# Korelasi


In [41]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [33]:
x = [8.0, 1,2,1.5,8, 17]
x_with_nan=[8.0, 1, 2, math.nan, 4, 28.0]
print(x)
print(x_with_nan)

[8.0, 1, 2, 1.5, 8, 17]
[8.0, 1, 2, nan, 4, 28.0]


In [44]:
y, y_with_nan=np.array(x), np.array(x_with_nan)
z, z_with_nan=pd.Series(x), pd.Series(x_with_nan)
print(y)
print(y_with_nan)
print(z)
print(z_with_nan)

[ 8.   1.   2.   1.5  8.  17. ]
[ 8.  1.  2. nan  4. 28.]
0     8.0
1     1.0
2     2.0
3     1.5
4     8.0
5    17.0
dtype: float64
0     8.0
1     1.0
2     2.0
3     NaN
4     4.0
5    28.0
dtype: float64


In [11]:
mean_=sum(y)/len(y)
mean2=np.mean(y)
mean2
mean_

6.0

In [12]:
mean_z=np.mean(z)
mean_z

6.0

In [13]:
mean_nan=np.mean(y_with_nan)
mean_nan

nan

In [15]:
n=len(y)
if n % 2:
    median_=sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index=sorted(x), round(0.5*n)
    median_=0.5*(x_ord[index-1]+x_ord[index])
    
median_

5

In [16]:
median_=np.median(y)
median_

5.0

In [18]:
median_z=np.median(z)
median_z

5.0

In [22]:
mode_y=statistics.mode(y)
mode_y

8.0

In [26]:
print(y.mean())
print(z_with_nan.mean())

6.0
8.6


In [34]:
#weighted mean
w=[0.7, 0.8, 0.1, 0.2, 0.3, 0.7]
wmean=sum(w[i] * x[i] for i in range(len(x)))/sum(w)
wmean

7.57142857142857

In [46]:
wmeannp=np.average(y, weights = w)
wmeannp

7.57142857142857

In [47]:
# Harmonic mean seorang bapak jalan kaki 5 km pertama dengan kecepatan 2 km/jam dan 5 km kemudian dengan kecepatan 4 km/jam
#n / sigma(1/n)
harmonicmean=len(x)/sum(1/i for i in x)

In [48]:
harmonicmean

2.423762376237624

In [49]:
harmonic_stat=statistics.harmonic_mean(x)
harmonic_stat

2.4237623762376237

In [51]:
harmonimean_scipy=scipy.stats.hmean(x)
harmonimean_scipy

2.423762376237624

In [53]:
# Geometric mean
#laptop 1 harga 20jt lama pakai 7 tahun
#laptop 2 harga 12jt lama pakai 4 tahun
#laptop 1 geometrik mean nya 
geoMeanLaptop1 = math.sqrt (1/20 * 7)
geoMeanLaptop2=math.sqrt(1/12 * 4)
geoMeanLaptop1
geoMeanLaptop2

0.5773502691896257

In [58]:
# Median (Nilai tengah)
# cara hitung median urutkan dari besar ke kecil, jika n/2=0 median n/2, jika n/2 != 0 median index[(n+1/2)] 
MedianData=[0.7, 0.8, 0.1, 0.2, 0.3, 0.7]
MedianData.sort()
MedianData

[0.1, 0.2, 0.3, 0.7, 0.7, 0.8]

In [60]:
medianstat=statistics.median_high(MedianData)
medianstat

0.7

In [61]:
medianstat=statistics.median_low(MedianData)
medianstat

0.3

In [70]:
#Modus
modusData=[1,1,1,3,4,5,6,7,8,9,1]
modus=max(((modusData.count(item),item) for item in set(modusData)))[1]
modus

1

In [71]:
modusStat=statistics.mode(modusData)
modusStat

1

In [78]:
# variability
variancestate= statistics.variance(modusData)
mean_=sum(modusData)/len(modusData)
variance=sum((item - mean_)**2 for item in modusData)/ (len(modusData) - 1)
print(variancestate, variance)

9.163636363636364 9.163636363636362


In [79]:
stdv=math.sqrt(variance)
stdvState=statistics.stdev(modusData)
print(stdv, stdvState)

3.027149874657078 3.027149874657078


In [80]:
# skewnes
skewnes=scipy.stats.skew(modusData)
skewnes

0.24935156205469858

In [83]:
# percentile
fivepercentile = np.percentile(modusData, 90)
fivepercentile

8.0

In [84]:
# range = max val - min val
range_=max(modusData) - min(modusData)
range_

8

In [85]:
describeData = scipy.stats.describe(modusData)
describeData

DescribeResult(nobs=11, minmax=(1, 9), mean=4.181818181818182, variance=9.163636363636364, skewness=0.24935156205469858, kurtosis=-1.3784722222222225)

In [92]:
x=list(range(0, 10))
y = np.random.rand(10)
print(x, y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [0.72492547 0.81651615 0.30801663 0.40910265 0.54691411 0.31612193
 0.55350651 0.18875651 0.9655051  0.92999269]


In [93]:
covarianxy=np.cov(x,y)
covarianxy

array([[9.16666667, 0.13859147],
       [0.13859147, 0.07506308]])

In [95]:
# 2D Data
twod = np.array([
    [1,1,1],
    [1,2,4],
    [4,8,9],
    [5,6,7]
])
twod

array([[1, 1, 1],
       [1, 2, 4],
       [4, 8, 9],
       [5, 6, 7]])

In [96]:
np.mean(twod)

4.083333333333333

In [97]:
twod.mean()

4.083333333333333

In [99]:
np.median(twod)

4.0

In [101]:
xmed = np.mean(twod, axis=0)
ymed = np.mean(twod, axis=1)
print(xmed, ymed)

[2.75 4.25 5.25] [1.         2.33333333 7.         6.        ]


In [102]:
scipy.stats.gmean(twod)

array([2.11474253, 3.13016916, 3.9842826 ])

In [103]:
scipy.stats.gmean(twod, axis=1)

array([1.        , 2.        , 6.6038545 , 5.94392195])

In [104]:
scipy.stats.describe(twod)

DescribeResult(nobs=4, minmax=(array([1, 1, 1]), array([5, 8, 9])), mean=array([2.75, 4.25, 5.25]), variance=array([ 4.25      , 10.91666667, 12.25      ]), skewness=array([ 0.11531718,  0.13205603, -0.18515606]), kurtosis=array([-1.84775087, -1.71586737, -1.41302235]))

In [108]:
# Dataframe
row_names =[1,2,3,4]
col_name = ["a","b","c"]

df =pd.DataFrame(twod, index = row_names, columns= col_name)
df

a  b  c
1  1  1  1
2  1  2  4
3  4  8  9
4  5  6  7

In [109]:
df.mean()

a    2.75
b    4.25
c    5.25
dtype: float64

In [110]:
df["a"].mean()

2.75

In [111]:
df.median()

a    2.5
b    4.0
c    5.5
dtype: float64

In [113]:
df.var()

a     4.250000
b    10.916667
c    12.250000
dtype: float64

In [114]:
df.mean().mean()

4.083333333333333

In [115]:
df.describe()

a         b     c
count  4.000000  4.000000  4.00
mean   2.750000  4.250000  5.25
std    2.061553  3.304038  3.50
min    1.000000  1.000000  1.00
25%    1.000000  1.750000  3.25
50%    2.500000  4.000000  5.50
75%    4.250000  6.500000  7.50
max    5.000000  8.000000  9.00